### ISSUE TITLE
Error while running recognize.py

### ISSUE THREAD

**Issue by atanumandal0491** [EN10/STT#2]
health@health-desktop:~/Desktop/lang_detec/Speech-to-Text-WaveNet-master$ python recognize.py --file test.wav
/usr/local/lib/python2.7/dist-packages/numba/errors.py:104: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)
INFO:tensorflow:0121:18:16:26.521:data.py:41] VCTK vocabulary loaded.
Traceback (most recent call last):
  File "recognize.py", line 92, in <module>
    mfcc = np.transpose(np.expand_dims(librosa.feature.mfcc(wav, sr), axis=0), [0, 2, 1])
  File "/usr/local/lib/python2.7/dist-packages/librosa/feature/spectral.py", line 1279, in mfcc
    S = power_to_db(melspectrogram(y=y, sr=sr, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/librosa/feature/spectral.py", line 1371, in melspectrogram
    mel_basis = filters.mel(sr, n_fft, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/librosa/filters.py", line 238, in mel
    lower = -ramps[i] / fdiff[i]
ValueError: operands could not be broadcast together with shapes (1,1025) (0,)

**Comment by atanumandal0491** [comment]
just upgraded the librosa and it is working. Thanks
